blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
	 path('', views.view_posts, name = 'view_posts')
    ,path('post/<int:post_pk>/', views.view_post, name = 'view_post')
    # ,path('comments/<int:post_pk>/<int:page>/',views.view_comments, name = 'view_comments') --> Deprecated
]

comics/urls.py
from django.urls import path
from . import views

app_name = "comics"
urlpatterns = [
    path('', views.index, name='comic_index')
    ,path('<int:comic_pk>/',views.view_panel, name ='view_panel')
    ,path('archive/', views.view_archive, name = 'view_archive')
    #,path('comments/<int:comic_pk>/<int:page>/', views.view_comments, name = 'view_comments') --> Deprecated
    ,path('auto_complete_chapter/', views.auto_complete_chapter, name = 'auto_complete_chapter')
    ,path('auto_complete_page/', views.auto_complete_page, name = 'auto_complete_page')
]

theengirls/urls.py
"""theengirls URL Configuration

"""
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views
from content import views as content_views, one_time_load

one_time_load.load_default_content()

urlpatterns = [
	path('', content_views.landing_page, name = "landing_page") # Home URL
	,path('comics/', include('comics.urls')) # comic app URLS
	,path('blog/',include('blog.urls')) # blog URLS
    ,path('comments/', include('comments.urls')) # comment URLS
    ,path('content/',include('content.urls')) # content URLS
    ,path('subscriptions/', include('subscriptions.urls')) # subscription URLS
	,path('admin/', admin.site.urls) # Django Admin URLS
    ,path('accounts/', include('django.contrib.auth.urls')) # Django User Auth URLS
    ,path('oauth/', include('social_django.urls', namespace='social'))  # Social App URLS 
    ,path('ckeditor/', include('ckeditor_uploader.urls')) # CK Editor
    ,path('privacy_policy/', views.privacy_policy, name = "privacy_policy")
    ,path('privacy_policy_source/', views.privacy_policy_source, name = "privacy_policy_source")
    ,path('logout/', views.logout_page, name="custom_logout")
    #,path('about/', about_page, name= "about")
    #,path('about_source/', about_source, name= "about_source")
    #,path('meet_the_engirls/', meet_the_engirls, name = "meet_the_engirls")
    #,path('meet_the_engirls_source/', meet_the_engirls_source, name = "meet_the_engirls_source")


]  
#if settings.DEBUG:
#    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # Media Files
#urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

#handler404 = error_404

comics/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from PIL import Image
import os
from io import StringIO,BytesIO
import datetime
from django.core.files.uploadedfile import SimpleUploadedFile
from django.utils import timezone
from django.conf import settings
from .url_changer import change_url
from .CropImage import cropped_thumbnail
import _thread as thread
from subscriptions.utils import send_new_comic_email

"""
	Return: 
		str Name of the main series 
"""
def getMainSeriesName():
	return settings.MAIN_SERIES_NAME

"""
	Comic Panel Object  
"""
class ComicPanel(models.Model):

	# Title of our comic/ youtube video
	title = models.CharField(max_length = 255)	

	# User uploaded image for the comic/youtube video (If a youtube video this image will be used for the thumbnail)
	image = models.ImageField(upload_to = 'comics/') 
	
	# The youtube URL (optional)
	youtube_url = models.URLField(max_length=250, null = True, blank = True, help_text = "Insert a Youtube URL if you want a video for a comic")
	
	# Our description 
	description = RichTextUploadingField()

	# Custom Caption 
	caption = models.CharField(max_length = 500)

	# Series, defaults to settings.MAIN_SERIES_NAME
	series = models.CharField(max_length = 255, null = False, blank = False, default = getMainSeriesName, 
		help_text="The default value is what the main Series Name is set to in Settings.py" )

	# Chapter, optional
	chapter = models.FloatField(null = True, blank = True)

	# page, optional
	page = models.IntegerField(null = True, blank = True, name="page")

	# Send emails? 
	send_emails = models.BooleanField(default= True)

	# Time of upload
	uploadTime = models.DateField(default=timezone.now)

	# Thumbnail of the picture
	thumbnail = models.ImageField(
		upload_to='comics/thumbnails/',
		null=True,
		blank=True)  # the small 200x200 picture object   

	class Meta:
		constraints = [
			models.UniqueConstraint(fields=['series','chapter', 'page'], name='Must be null or unique')
			]

	def __str__(self):
		return self.title


	"""
		Generates Thumbnail. Saves in Media location /thumbnails
	"""
	def generateThumbnail(self):
			
		if self.image.name.endswith(".jpg"):
			PIL_TYPE = 'jpeg'
			FILE_EXTENSION = 'jpg'
			DJANGO_TYPE = 'image/jpeg'

		elif self.image.name.endswith(".png"):
			PIL_TYPE = 'png'
			FILE_EXTENSION = 'png'
			DJANGO_TYPE = 'image/png'

		instance = self.image

		try:
			instance.open()
		except Exception as e:
			print("Error opening instance image")
			return
		# Open original photo which we want to thumbnail using PIL's Image

		try:
			image = Image.open(BytesIO(instance.read()))
		except IOError as e:
			print("Error opening in memory file: " + str(e))
			return

		# Crop out 1/4 the larger dimension of the image
		if image.height >= image.width:
			image = image.crop( tuple( (0, 0, int(round(image.width)), int(round(image.height-image.height/4)))) )
		elif image.width > image.height:
			image = image.crop( tuple( (0, 0 , int(round(image.width - image.width/4)), int(round(image.height)))) )

		# Send the cropped image to be resized to the sandard thumbnail size
		image = cropped_thumbnail(image)

		# Save the thumbnail
		temp_handle = BytesIO()
		try:
			image.save(temp_handle, PIL_TYPE)
		except KeyError as e:
			print("Error when saving in memory file " + str(e))
			return
		except IOError as e:
			print("Error when saving in memory file " + str(e))
			return

		if settings.DEBUG:
			print("Successfully saved in memory thumbnail")

		try:
			temp_handle.seek(0)
		except EOFError as e:
			print("Error when seeking in memory file: " + str(e))

		# Save image to a SimpleUploadedFile which can be saved into
		# ImageField
		try:
			suf = SimpleUploadedFile(os.path.split(instance.name)[-1],
					temp_handle.read(), content_type=DJANGO_TYPE)
		except FileNotFoundError:
			if settings.DEBUG:
				print("Error in simple file upload")
				return
		except Exception: 
			print("Error while creating thumbnail")
			return

		try:
			# Save SimpleUploadedFile into image field
			self.thumbnail.save(
				'%s_thumbnail.%s' % (os.path.splitext(suf.name)[0], FILE_EXTENSION),
				suf,
				save=False
			)
		except exception as e:
			print("Error saving thumbnail file to image field" + str(e))
			return

	"""
		Save -
		1) Generate Thumbnail
		2) Generate youtube_url (if any)
		3) Send emails
	"""
	def save(self):
		#self.set_thumbnail_resize()
		self.generateThumbnail()
		self.youtube_url = change_url(self.youtube_url)

		if self.send_emails:
			try:
				thread.start_new_thread( send_new_comic_email,  (self.title, ) )
			except Exception as e:
				print("Unable to start new thread-{}\n Unable to send emails".format(str(e)))

		#self.image.open()
		super(ComicPanel, self).save()

comments/forms.py
from django import forms 

from .models import Comment
#from dal import autocomplete


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        widgets = {
          'body': forms.Textarea(attrs={'rows':2, 'cols':20}),
        }
    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['body'].label = "Say Something:" 


#Just use comment form for now
class ReplyForm(forms.ModelForm):
	body = forms.CharField(max_length = 3000, widget=forms.TextInput(attrs={'class':'reply_input_body'}))
	class Meta:
		model = Comment
		fields = ('body',)

	def __init__(self, *args, **kwargs):
		super(ReplyForm, self).__init__(*args, **kwargs)
		self.fields['body'].label = "" 

comics/views.py
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse, Http404, JsonResponse
from django.conf import settings
from django.db.models import F
from .filters import ComicPanelFilter
from .models import ComicPanel#, Comment
from comments.forms import CommentForm
from social_django.models import UserSocialAuth
from django.db.utils import OperationalError
from dal import autocomplete


"""
View for most recent comic

Returns views.ViewPanel(comic_pk = most recent comic_pk )
"""
def index(request):
	if request.method == 'GET':

		# Let's find the most recent comic!
		comic_to_display= None

		# Make sure there is a series labeled 'main'
		if ComicPanel.objects.filter(series=settings.MAIN_SERIES_NAME).exists():
		
			# Get the chapters for the main series
			chapter_dicts = ComicPanel.objects.filter(series=settings.MAIN_SERIES_NAME).values('chapter').distinct()
			chapters = []
			for item in chapter_dicts:
				if item['chapter']:
					chapters.append(item['chapter'])

			if chapters:
				finalChapter = max(chapters)
				comic_to_display = ComicPanel.objects.filter(
					series=settings.MAIN_SERIES_NAME,
					chapter=finalChapter
					).order_by(F("page").desc(nulls_last = True)).first()
			
			# If there are not chapters...
			else:
				comic_to_display = ComicPanel.objects.all().order_by("-uploadTime").first()

		# If, for some reason, there is no main series
		else:
			comic_to_display = ComicPanel.objects.all().order_by("-uploadTime").first()

		# Null Check
		if comic_to_display:
			return view_panel(request, comic_to_display.pk)
		else: 
			return view_panel(request)


"""
Return dictionary of chapters per series
I.E. 

{
	"1.0": {
		"id":1.0,
		"name": 1.0
	},
	"2.0":{ ... }
}
"""
def auto_complete_chapter(request):
	series = request.GET.get('series', None)
	data = {}

	if series:
		chapters_list = []	
		if series:
			chapters_dicts = ComicPanel.objects.filter(series = series).values_list('chapter').distinct()
			chapters_list = [(item[0],item[0]) for item in chapters_dicts]
			data = { chapter[0]: {'id': chapter[0], 'name': chapter[1] } for chapter in chapters_list}	

	return JsonResponse(data)

def auto_complete_page(request):
	series = request.GET.get('series', None)
	chapter = request.GET.get('chapter', None)
	data = {}

	if series and chapter:
		pages_dicts = ComicPanel.objects.filter(series = series, chapter = chapter).values_list('page').distinct()
		page_list = [(item[0], item[0]) for item in pages_dicts]
		data = {page[0]: {'id':page[0], 'name':page[1]} for page in page_list}

	return JsonResponse(data)
	
"""
View Archive

GET requests only

"""
def view_archive(request):

	comic_list = ComicPanel.objects.order_by('series', 'chapter', 'page')
	filter_list = {}

	if request.GET.get('series', None):
		filter_list['series__exact'] = request.GET.get('series')

	if request.GET.get('chapter', None) and request.GET.get('chapter') is not 'null':
		filter_list['chapter__exact'] = request.GET.get('chapter')

	if request.GET.get('page', None) and request.GET.get('page') is not 'null':
		filter_list['page__exact'] = request.GET.get('page')

	comic_list = comic_list.filter(**filter_list)

	comic_filter = ComicPanelFilter(request.GET, queryset=comic_list)
	paginator = Paginator(comic_filter.qs, settings.COMIC_PAGINATOR_COUNT)

	page = request.GET.get('web_page', 1)
	try:
		comics = paginator.page(page)
	except (PageNotAnInteger, TypeError):
		comics = paginator.page(1)
	except EmptyPage:
		comics = paginator.page(paginator.num_pages)

	return render(request, 'comics/comic_archive.html', context = {'filter': comic_filter, 'comics': comics})	

"""
View for specific comic

GET Requests only

"""
def view_panel(request, comic_pk =-1 ):

	comic_panel = None
	newest_comic_pk = -1
	oldest_comic_pk = -1
	next_comic_pk = -1
	prev_comic_pk = -1
	comment_form = CommentForm()

	#print("comic_pk:{}".format(str(comic_pk)))
	# Try to get comment with given pk. Return default values otherwise
	try:
		comic_panel = ComicPanel.objects.all().get(pk=comic_pk)
	except ObjectDoesNotExist:
		raise Http404

	# Get chapters
	chapter_dicts = ComicPanel.objects.filter(series = comic_panel.series).values('chapter').distinct()
	chapters = []
	for item in chapter_dicts:
		if item['chapter']:
			chapters.append(item['chapter'])         

	# If Chapters exists
	if chapters and comic_panel.chapter is not None:

		finalChapter = max(chapters)
		newest_comic_pk = ComicPanel.objects.filter(
			series = comic_panel.series, 
			chapter=finalChapter).order_by(F("page").desc(nulls_last=True)).first().pk


		firstChapter = min(chapters)
		oldest_comic_pk = final_comic = ComicPanel.objects.filter(
			series = comic_panel.series, chapter=firstChapter).order_by(F("page").asc(nulls_last=True)).first().pk

		# Do we have a page? Find the next, previous and first
		if comic_panel.page:

			# Is the next page in the current chaper?
			if ComicPanel.objects.filter(series = comic_panel.series, chapter=comic_panel.chapter, page = comic_panel.page+1).exists():
				next_comic_pk = ComicPanel.objects.all().get(
						series=comic_panel.series, chapter=comic_panel.chapter, page=comic_panel.page + 1).pk 
				
			# Is the next page in another chaper?
			elif comic_panel.chapter +1 in chapters:
				next_comic_pk = ComicPanel.objects.all().get(
					series = comic_panel.series,
					chapter = comic_panel.chapter+1, 
					page = ComicPanel.objects.filter(
						chapter = comic_panel.chapter +1).order_by(F("page").asc(nulls_last=True)).first().page).pk
					
			# Is the previous page in the current chapter?
			if ComicPanel.objects.filter(series = comic_panel.series, chapter=comic_panel.chapter, page = comic_panel.page -1).exists():
				prev_comic_pk = ComicPanel.objects.all().get(
					series = comic_panel.series, 
					chapter=comic_panel.chapter, 
					page = comic_panel.page -1).pk

			# Is the previous page in the previous chapter?
			elif comic_panel.chapter -1 in chapters:

				#Find the last page in the previous chapter  
				prev_comic_pk = ComicPanel.objects.all().get(
					series = comic_panel.series,
					chapter=comic_panel.chapter -1, 
					page=ComicPanel.objects.filter(
						chapter = comic_panel.chapter -1).order_by(F("page").desc(nulls_last=True)).first().page).pk
			
	return render(request, 'comics/comic_panel_view.html',
		context = {'comic_panel': comic_panel,
		'newest_comic_pk': newest_comic_pk,
		'oldest_comic_pk': oldest_comic_pk,
		'prev_comic_pk' : prev_comic_pk,
		'next_comic_pk': next_comic_pk,
		'comment_form':comment_form
									  })
#def view_blog_comments(request, post)

comics/templates/comics/comic_archive.html
{% extends "base.html" %}
{% block main_content %}

{% load static %}
<link href="{% static 'css/blog-post.css' %}" rel="stylesheet">


<div class = "container-fluid">	
	<div class = "page-header text-center pb-2 engirls_font_large title_animation" style = ""> Engirls Comic Archive</div>		
		
	<!-- <hr> -->
	<div class = "row flex-xl-nowrap" id = "">
		<div id = "" class="pl-2 pb-4 slide_left" style = "">
			<p><b>Filter Comics</b></p>
			<div class = "">
				
				<form id= "engirls_filter_form" class="form theengirls_onchange" method="GET">
					 	
					{% csrf_token %}

					{% for field in filter.form %}	
						<div class = "engirls_font_norm col-sm-2 pb-1" id="field_name_{{ field.name }}">
						 {{ field.name }}
						 {{ field }}
						</div>
						<hr>
					{% endfor %}	
					<button id = "theengirls_submit_filter" type="submit" style = "display:none;">Filter</button>
						
				</form>	
			</div>
		</div>


		<!-- card deck -->
		<!-- Smaller viewpoerts, the cards must take up more col space. Or go out of bounds -->
		<div class = "card-deck col-sm-12 col-md-12 col-lg-10">
			{% for comic in comics %}									
				<div class="col-lg-3 col-md-4 col-sm-5" style = ""> 
					<!-- min width... gets too small on medium sized screens --> 
					<div class="card mb-sm-5 shadow" style="" >
							
							{% if comic.thumbnail %}
								<a href="{% url 'comics:view_panel' comic_pk=comic.pk %}">
									<!-- max height to limit comics that are too long -->
									<img class="card-img-top img-fluid" style ="max-height: 400px;" src="{{ comic.thumbnail.url }}" />
								</a>	
								
							{% else %}	
								<div class = "col text-center">
									<a href="{% url 'comics:view_panel' comic_pk=comic.pk %}">
										<h5 class= "engirls_font_large"> No image available</h5>
									</a>
								</div>
								
							{% endif %}
							
			  			<div class = "card-header engirls_font_norm"><h5> {{ comic.title }}</h5> </div>

			  			 <div class="card-footer text-muted">
			  			 	 <div class = "container">
			  			 	 	<div class = "row">		
						  			<small> Series: <b>{{ comic.series }} </b> </small> 	
			  			 		</div>
			  			 		<div class = "row">
									<small>Chapter: <b>{{ comic.chapter }} </b> </small>
			  			 		</div>
			  			 		<div class = "row">
									<small> Page: <b>{{ comic.page }} </b> </small>			  			 			
			  			 		</div>
			  			 	</div>
			  			 	
			  			 </div>					
					</div> 
				</div>
			{% endfor %}
		</div>
	</div>

	<!-- if no comics -->
	{% if not comics %}

		<div class = row>
			<div class = "col-sm-3"></div>
	 		<div class = "col-sm engirls_font_large text-center"> Looks like there are no comics :( </div>
			<div class = "col-sm-3"></div>	
		</div>	
		
	{% endif %}

	<hr>
	<!-- 3rd row -->
	<div class = "row py-3 ml-2">

		<div class="pagination d-flex align-items-center">
		  	<div class = "col-sm-4 mr-2 engirls_font_norm">
		      	Pages: 
		     </div>
			{% if comics.paginator.num_pages > 1 %}
				{% for num in comics.paginator.page_range %}
					<div class = "col-sm-3 engirls_font_norm">
						<!-- Current page number -->
						{% if comics.number == num %}
							<!-- If there is existing query parameters -->
						 	{% if 'series' in request.get_full_path %}
						 		<h5><a class="text-primary" href="{{ request.get_full_path }}&web_page={{ num }}" >{{ num }}</a></h5>
						 	{% else %}
								<h5><a class="text-primary" href="{% url 'comics:view_archive' %}?web_page={{ num }}" >{{ num }}</a></h5>
						 	{% endif %}

							 <!-- Other page numbers -->
						{% else %}
							{% if 'series' in request.get_full_path %}
								<h5><a class="text-secondary" href="{{ request.get_full_path }}&web_page={{ num }}">{{ num }}</a></h5>
							{%  else %}
								<h5><a class="text-secondary" href="{% url 'comics:view_archive' %}?web_page={{ num }}" >{{ num }}</a></h5>
							{% endif %}
						{% endif %}
					</div>
				{% endfor %}
			{% endif %}
		</div>
	</div>


<!-- comic container-->
</div>

<script>

/* 
	Retreive list of chapters given series
*/
function get_chapters(){
	//alert("click click, bitch");
	return $.ajax({
		url: '/auto_complete_chapter/',
		type: 'GET',
		data: {
		  'series': $("#id_series").val(),
		},
		dataType: 'json',
		success: function(data) {
			//alert("success!")     		
		},
		error: function(data) {
			//alert("Error")
		},
	  });
	  //return false;
};

/* 
	Retreive list of pages given series and chapter
*/
function get_pages(){
	//alert("click click, bitch");
	return $.ajax({
		url: '/auto_complete_page/',
		type: 'GET',
		data: {
		  'series': $("#id_series").val(),
		  'chapter': $("#id_chapter").val(),
		},
		dataType: 'json',
		success: function(data) {
			//alert("success!")     		
		},
		error: function(data) {
			//alert("Error")
		},
	  });
	  //return false;
};

/* 
	Chapter and page values must be loaded via ajax
*/
$(document).ready(function(){
	// To style all selects
	$(".Filter_Button").on("click", function(e){
		e.preventDefault();
		$("#hide_filter_form").toggle();
	});
	$("#id_chapter").empty();
	$('#id_page').empty();
	//$('select').selectpicker();
	const urlParams = new URLSearchParams(window.location.search);

	// 1) get chapters
	get_chapters().done(function(data){ 

		// alert("We done bitch")
		const cur_chapter = urlParams.get('chapter');
		//var chapters_list = []
	    for( var item in data) {
	        var id = data[item]['id'];
	        var name = data[item]['name'];
	    	$("#id_chapter").append("<option value=\'"+id+ "\' selected= \'\' >" +name+ "</option>" );
	    	//chapters_list.push(id);
	    }
		$("#id_chapter").append("<option value=\'\' selected= \'\' >All</option>" );
		// Make sure series is not null
		//if(urlParams.get('series') != '' && urlParams.get('series') != null) {
			$("#id_chapter").val(cur_chapter);
		//}else {
		//	$("#id_chapter").val('');
		//}
		

		return false;

	// 2) get pages
	}).done(function(results) {
		//alert("Second done!");
		// Get our pages
		get_pages().done(function(data){ 
			//alert("Done getting pages");
			const cur_page = urlParams.get('page');
		    for( var item in data) {
		        var id = data[item]['id'];
		        var name = data[item]['name'];
		    	$("#id_page").append("<option value=\'"+id+ "\' selected= \'\' >" +name+ "</option>" );
		    }
			$("#id_page").append("<option value=\'\' selected= \'\' >All</option>" );
			
			// Make sure chapter is not null
			//if(urlParams.get('chapter') != null && urlParams.get('chapter') != '' ) {
				$("#id_page").val(cur_page);
			//}else{
			//	$("#id_page").val('');
			//}
						
		});

		return false;
	}); 

	// alert($("#id_chapter").val())
	// Toggle display of filter form
	// If series not selected...
	if(urlParams.get('series') == null || urlParams.get('series') == '')
	{
		// Hide Chapter, page if series is not selected
		$("#field_name_chapter").css("display", "None");
		$("#id_chapter").css("display", "None");

		$("#field_name_page").css("display", "None");
		$("#id_page").css("display", "None");

	// If series is selected
	}else{
		// Show chapter otherwise
		$("#field_name_chapter").css("display", "show");
		$("#id_chapter").css("display", "show");
	}

	if( urlParams.get('chapter') == null || urlParams.get('chapter') == '') {

		$("#field_name_page").css("display", "None");
		$("#id_page").css("display", "None");	
		//alert("Chapter is null" + $("#id_chapter").val());
	}else if ( (urlParams.get('series') != null && urlParams.get('series') != '')  && (urlParams.get('chapter') != null && urlParams.get('chapter') != '')) {
		//alert("chapter is not null!");
		$("#field_name_page").css("display", "show");
		$("#id_page").css("display", "show");
	}


	return false;
});

/* 
	Every time filter form changes, submit the form
*/
$(".theengirls_onchange" ).change(function() {
	// Cluck cubmit

	if($("#id_series").val() == null || $("#id_series").val() == '') {
		$("#id_chapter").val('');
		$("#id_page").val('');
	}

	if($("#id_chapter").val() == null || $("#id_chapter").val() == '') {
		$("#id_page").val('');
	}	
	$("#theengirls_submit_filter").click();
});	


</script>

{% endblock %}

{% block footer %}
    {% include "footer.html" %}
{% endblock %}