blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
	 path('', views.view_posts, name = 'view_posts')
    ,path('post/<int:post_pk>/', views.view_post, name = 'view_post')
    # ,path('comments/<int:post_pk>/<int:page>/',views.view_comments, name = 'view_comments') --> Deprecated
]

subscriptions/urls.py
from django.urls import path
from . import views

"""
	Some bitchin URLS
"""
app_name = "subscriptions"
urlpatterns = [
    #path('test', views.test, name='test')
    #,path('test2', views.test2, name= 'test2')
    path('submit_subscription/', views.submit_subscription, name = 'submit_subscription')
    ,path('subscribe/', views.subscribe, name = 'subscribe')
    ,path('unsubscribe/', views.unsubscribe, name = 'unsubscribe') 

]

theengirls/urls.py
"""theengirls URL Configuration

"""
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views
from content import views as content_views, one_time_load

one_time_load.load_default_content()

urlpatterns = [
	path('', content_views.landing_page, name = "landing_page") # Home URL
	,path('comics/', include('comics.urls')) # comic app URLS
	,path('blog/',include('blog.urls')) # blog URLS
    ,path('comments/', include('comments.urls')) # comment URLS
    ,path('content/',include('content.urls')) # content URLS
    ,path('subscriptions/', include('subscriptions.urls')) # subscription URLS
	,path('admin/', admin.site.urls) # Django Admin URLS
    ,path('accounts/', include('django.contrib.auth.urls')) # Django User Auth URLS
    ,path('oauth/', include('social_django.urls', namespace='social'))  # Social App URLS 
    ,path('ckeditor/', include('ckeditor_uploader.urls')) # CK Editor
    ,path('privacy_policy/', views.privacy_policy, name = "privacy_policy")
    ,path('privacy_policy_source/', views.privacy_policy_source, name = "privacy_policy_source")
    ,path('logout/', views.logout_page, name="custom_logout")
    #,path('about/', about_page, name= "about")
    #,path('about_source/', about_source, name= "about_source")
    #,path('meet_the_engirls/', meet_the_engirls, name = "meet_the_engirls")
    #,path('meet_the_engirls_source/', meet_the_engirls_source, name = "meet_the_engirls_source")


]  
#if settings.DEBUG:
#    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # Media Files
#urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

#handler404 = error_404

subscriptions/models.py
from django.db import models
from django.utils import timezone
from ckeditor_uploader.fields import RichTextUploadingField
import _thread as thread

""" 
	Subscription Model

"""
class Subscription(models.Model):

    email = models.EmailField(blank = False, null = False, unique = True)

    key = models.CharField(max_length= 20, blank = True)

    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_on',)

    def __str__(self):
        return 'Email: {} key: {} created on: {}'.format(self.email, self.key, str(self.created_on))

"""
	CustomEmail Class

	Send a custom email to everyone in the subscription class
"""
class CustomEmail(models.Model):
	
	subject = models.CharField(max_length=255)

	"""
	TODO: 
	custom_recipients = models.CharField(max_length = 3000, 	
		null = True, 
		blank = True, 
		help_text = "Leave blank if you want to send to everyone in 'Subscriptions'. Seperate with comma")
	"""

	body = RichTextUploadingField()
	
	send_now = models.BooleanField(default = True, 
		help_text = "If this box is checked, the email will be sent directly after you press 'save'") 

	date_sent = models.DateTimeField(null = True, blank = True)

	""" 
		send custom email()
	"""
	def send_custom_email(self):
		if not self.send_now:
			return False

		context = {}
		context["body"] = self.body

		# Prevent the circle!!!!! 
		from subscriptions.utils import mass_mail_thread_helper

		"""
		TODO: 
		if self.custom_recipients:

			print("Sending to custom recipient(s): {}".format(self.custom_recipients))
			parsed_recipients = [x.strip() for x in self.custom_recipients.split(',')]
			recipient_tuples = []

			for recipient in parsed_recipients:
				subscription

			try:
				thread.start_new_thread( mass_mail_thread_helper,  
					('email_custom.html', self.subject,  context, parsed_recipients) )
			except Exception as e:
				print(str(e))
				return False

		# If recipients is none
		else:
		"""
		try:
			thread.start_new_thread(mass_mail_thread_helper, ('email_custom.html', self.subject, context))
		except Exception as e:
			print(str(e))
			return False

		self.date_sent = timezone.now()
		# All is good!
		return True
	
	def __str__(self):
		return 'Subject: {}, Sent On: {}'.format(self.subject, str(self.date_sent))

	
	def save(self):
		if self.save:
			self.send_custom_email()
		super(CustomEmail, self).save()

subscriptions/forms.py
from django import forms 
from .models import Subscription
#from dal import autocomplete


class SubscriptionForm(forms.ModelForm):
    class Meta:
        model = Subscription
        fields = ('email',)

subscriptions/views.py
from django.shortcuts import render
from django.conf import settings
from content.models import Content
import random
import string
from .models import Subscription 
from .forms import SubscriptionForm  
from django.http import HttpResponse, HttpResponseBadRequest, Http404, JsonResponse, HttpResponseForbidden 
from .utils import create_subscription, send_thank_you
import _thread as thread
from ratelimit.decorators import ratelimit

"""
	Render Subscription form
"""
def subscribe(request):
	
	if request.method != 'GET':
		return HttpResponseBadRequest("Must be a GET request")
	subscription_form = SubscriptionForm()
	return render(request, "subscriptions/subscribe.html", context = {"subscription_form":subscription_form})

"""
	Unsubscribe
"""
@ratelimit(key='ip', rate='10/h', block=True)
def unsubscribe(request, email_address =-1, key =-1):
	email_address = request.GET.get('email_address', None)
	key = request.GET.get('key', None)

	if request.method!= 'GET':
		return HttpResponseBadRequest("Must be a GET request to access this resource")
	sub = None	
	try:
		sub = Subscription.objects.get(email = email_address)
	except Subscription.DoesNotExist:
		return HttpResponseBadRequest("Email address does not exist")

	# Make sure user has the correct key
	if key == sub.key:
		sub.delete()
		content = None
		try:
			content = Content.objects.get(title = settings.CONTENT_KEY_NAMES.get('UNSUBSCRIBE_CONTENT_NAME',None))
		except content.DoesNotExist as d:
			print(str(d))

		return render(request, "Sorry_To_See_You_Leave.html", context = {"content": content})
	# If key does not match
	else: 
		return HttpResponseBadRequest("Looks like you don't have the right key...")


"""
	Submit subscription, with a post request
"""
@ratelimit(key='ip', rate='10/h', block=True)
def submit_subscription(request):
	if request.method != 'POST':
		return HttpResponseBadRequest("Must be a POST Request to access this resource")
	
	if not request.is_secure():
		return JsonResponse({"Response": "Looks like you're not on a secure connection. Try accessing the site through 'https' "})

	subscription_form = SubscriptionForm(request.POST)
	if subscription_form.is_valid():
		if not create_subscription(subscription_form):
			return JsonResponse({"Response":"We already got this email on record!"})
	# If there are errors in the subscription form
	else:
		return JsonResponse({"Response": subscription_form['email'].errors})

	# Try sending email in new thread
	try:
		thread.start_new_thread( send_thank_you, (subscription_form.cleaned_data['email'], ) )
	except Exception as e:
		print("Unable to start new thread-{}".format(str(e)))
		return JsonResponse({"Response": "Internal Server Error. Please try again soon :)"})

	#send_thank_you(subscription_form.cleaned_data['email'])
	return JsonResponse({"Response": "Got it, Thank You!"})

def custom_email(request):
	pass

subscriptions/templates/subscriptions/email_base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title>The Engirls Thank You</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<style type="text/css">
			* {
				-ms-text-size-adjust:100%;
				-webkit-text-size-adjust:none;
				-webkit-text-resize:100%;
				text-resize:100%;
			}
			a{
				outline:none;
				color:#40aceb;
				text-decoration:underline;
			}
			a:hover{text-decoration:none !important;}
			.nav a:hover{text-decoration:underline !important;}
			.title a:hover{text-decoration:underline !important;}
			.title-2 a:hover{text-decoration:underline !important;}
			.btn:hover{opacity:0.8;}
			.btn a:hover{text-decoration:none !important;}
			.btn{
				-webkit-transition:all 0.3s ease;
				-moz-transition:all 0.3s ease;
				-ms-transition:all 0.3s ease;
				transition:all 0.3s ease;
			}
			table td {border-collapse: collapse !important;}
			.ExternalClass, .ExternalClass a, .ExternalClass span, .ExternalClass b, .ExternalClass br, .ExternalClass p, .ExternalClass div{line-height:inherit;}
			@media only screen and (max-width:500px) {
				table[class="flexible"]{width:100% !important;}
				table[class="center"]{
					float:none !important;
					margin:0 auto !important;
				}
				*[class="hide"]{
					display:none !important;
					width:0 !important;
					height:0 !important;
					padding:0 !important;
					font-size:0 !important;
					line-height:0 !important;
				}
				td[class="img-flex"] img{
					width:100% !important;
					height:auto !important;
				}
				td[class="aligncenter"]{text-align:center !important;}
				th[class="flex"]{
					display:block !important;
					width:100% !important;
				}
				td[class="wrapper"]{padding:0 !important;}
				td[class="holder"]{padding:30px 15px 20px !important;}
				td[class="nav"]{
					padding:20px 0 0 !important;
					text-align:center !important;
				}
				td[class="h-auto"]{height:auto !important;}
				td[class="description"]{padding:30px 20px !important;}
				td[class="i-120"] img{
					width:120px !important;
					height:auto !important;
				}
				td[class="footer"]{padding:5px 20px 20px !important;}
				td[class="footer"] td[class="aligncenter"]{
					line-height:25px !important;
					padding:20px 0 0 !important;
				}
				tr[class="table-holder"]{
					display:table !important;
					width:100% !important;
				}
				th[class="thead"]{display:table-header-group !important; width:100% !important;}
				th[class="tfoot"]{display:table-footer-group !important; width:100% !important;}
			}
		</style>
	</head>
	<body style="margin:0; padding:0;" bgcolor="#eaeced">

		<table style="min-width:320px;" width="100%" cellspacing="0" cellpadding="0" bgcolor="#eaeced">
			<!-- fix for gmail -->
			<tr>
				<td class="hide">
					<table width="600" cellpadding="0" cellspacing="0" style="width:600px !important;">
						<tr>
							<td style="min-width:600px; font-size:0; line-height:0;">&nbsp;</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<table width="100%" cellpadding="0" cellspacing="0">
					<tr>
						<td bgcolor="#eaeced">
							<table class="flexible" width="600" align="center" style="margin:0 auto;" cellpadding="0" cellspacing="0">
								{% block custom_content %}
								{% endblock %}
							</table>
						</td>
					</tr>
				</table>
			</tr>
			<tr>

				<td class="wrapper" style="padding:0 10px;">
					<table width="100%" cellpadding="0" cellspacing="0">
						<tr>
							<td data-bgcolor="bg-module" bgcolor="#eaeced">
								<table class="flexible" width="600" align="center" style="margin:0 auto;" cellpadding="0" cellspacing="0">
									<tr>
										<td data-bgcolor="bg-block" class="holder" style="padding:58px 60px 52px;" bgcolor="#f9f9f9">
											<table width="100%" cellpadding="0" cellspacing="0">

											
												{% block main_content %}
   												{% endblock %}
												

												<tr>
													<td style="padding:0 0 20px;">
														<table width="134" align="center" style="margin:0 auto;" cellpadding="0" cellspacing="0">
															<tr>
																<td data-bgcolor="bg-button" data-size="size button" data-min="10" data-max="16" class="btn" align="center" style="font:12px/14px Arial, Helvetica, sans-serif; color:#f8f9fb; text-transform:uppercase; mso-padding-alt:12px 10px 10px; border-radius:2px;" bgcolor="#7bb84f">
																	<a target="_blank" style="text-decoration:none; color:#f8f9fb; display:block; padding:12px 10px 10px;" href="#">Go to Site</a>
																</td>
															</tr>
														</table>
													</td>
												</tr>

											</table>
										</td>
									</tr>
									<tr><td height="28"></td></tr>
								</table>
							</td>
						</tr>
					</table>
					
					<table width="100%" cellpadding="0" cellspacing="0">
						<tr>
							<td data-bgcolor="bg-module" bgcolor="#eaeced">
								<table class="flexible" width="600" align="center" style="margin:0 auto;" cellpadding="0" cellspacing="0">
									<tr>
										<td class="footer" style="padding:0 0 10px;">
											<table width="100%" cellpadding="0" cellspacing="0">
												<tr class="table-holder">
													<th class="tfoot" width="400" align="left" style="vertical-align:top; padding:0;">
														<table width="100%" cellpadding="0" cellspacing="0">
															<tr>
																<td data-color="text" data-link-color="link text color" data-link-style="text-decoration:underline; color:#797c82;" class="aligncenter" style="font:12px/16px Arial, Helvetica, sans-serif; color:#797c82; padding:0 0 10px;">
																	The Engirls, 2020. &nbsp; All Rights Reserved. <a target="_blank" style="text-decoration:underline; color:#797c82;" href="">Unsubscribe.</a>
																</td>
															</tr>
														</table>
													</th>
													<th class="thead" width="200" align="left" style="vertical-align:top; padding:0;">
														<table class="center" align="right" cellpadding="0" cellspacing="0">
															<tr>
																<!-- Facebook -->
																<td class="btn" valign="top" style="line-height:0; padding:3px 0 0;">
																	<a style="text-decoration:none;" href="#"><i class="fab fa-facebook-f"></i></a>
																</td>
																<td width="20"></td>

																<!-- IG -->
																<td class="btn" valign="top" style="line-height:0; padding:3px 0 0;">
																	<a style="text-decoration:none;" href="#"><i class="fab fa-instagram"></i></a>
																</td>

															</tr>
														</table>
													</th>
												</tr>
											</table>
										</td>
									</tr>
								</table>
							</td>
						</tr>
					</table>
				</td>
			</tr>

			<tr>
			</tr>
		</table>
	</body>
</html>

subscriptions/templates/subscriptions/subscribe.html
<!DOCTYPE HTML>
<html lang="en">

<body>			
	<div class = "container-fluid" name = "Subscription_Container">
		<div class = "">
			<div class = "row" style = "max-width: 100%;">
				<a class = "sub-button" data-toggle="collapse" href="#id_subscribe_form" aria-expanded="true" aria-controls="id_subscribe_form" style = "color:inherit;">
					<div class = "theengirls-border-right mr-2">
						<img src="https://img.icons8.com/bubbles/100/000000/email.png"/>
						<div id= "id_sign_up" class = "pr-2"> Sign up for email updates! </div>
					</div>
				</a>
			</div>
			<div class = "row" style = "max-width: 100%;">
				<div class = "collapse" id = "id_subscribe_form">
					<form action = "{% url 'subscriptions:submit_subscription' %}" method="POST">

					{% if user.is_authenticated and user.email %}
						<input type = "hidden" id = "id_user_email" value = "{{ user.email }}"> 
					{% else %}
						<input type = "hidden" id = "id_user_email" value = "false"> 
					{% endif %} 
						
						{% csrf_token %}
						{% for field in subscription_form %}
							 {{ field.errors }}
							 {{ field.label }}
							 {{ field }}
						{% endfor %}
						

						<button id = "id_subscribe_button" class= "button-submit btn-outline-dark btn-sm">Subscribe !</button>
					</form>
				</div>
			</div>
			<div class = "row">
				<div id = "id_form_response" class ="the_engirls_fonr_norm"> </div>
			</div>
		</div>

	</div>
</body>
<script>

/** 
	Submit Subscribe Button
**/
$("#id_subscribe_button").on('click', function(e) {
    e.preventDefault();
    
    var form = $(this).closest("form");
     $.ajax({
            url: '/subscriptions/submit_subscription/',
            type: 'POST',
            data: form.serialize()
        }).done(function(data){
        	// Set email forum to none
        	$("#id_email").val("");
        	// Display response message
        	$.each( data, function( key, val ) {
        		$("#id_form_response").text(val);
        		if (val == "Got it, Thank You!")
        		{
        			$("#id_subscribe_form").toggle();
        		}
        		
        	});
        });
      return false;
  });


$(document).ready(function(){
/**
	Fill in default email, if user is logged in
**/
	//alert("Whoo!");
	var email = $("#id_user_email").val();
	//alert("Email value: " + email)
	if(email !== "false") {
		$("#id_email").val(email);
	}
});
</script>

subscriptions/templates/subscriptions/test.html
<!DOCTYPE html>
<!-- Comment Body -->
<HTML lang="en">
<small> Don't want to keep seeing these?<a href = "theengirls.herokuapp.com">  Unsubscribe  </a> </small>
<body>
	
	<p><h1> Thanks for doing me a Subscribe! </h1></p>
</body>

subscriptions/templates/subscriptions/thanks.html
{% extends "subscriptions/email_base.html" %}

{% block custom_content %}
    {{ content.body | safe }}
{% endblock %}


{% block main_content %}
<tr>
	<td data-color="title" data-size="size title" data-min="25" data-max="45" data-link-color="link title color" data-link-style="text-decoration:none; color:#292c34;" class="title" align="center" style="font:35px/38px Arial, Helvetica, sans-serif; color:#292c34; padding:0 0 24px;">
		Thanks for Subscribing to the Engirls!
	</td>
</tr>

<tr>
	<td data-color="text" data-size="size text" data-min="10" data-max="26" data-link-color="link text color" data-link-style="font-weight:bold; text-decoration:underline; color:#40aceb;" align="center" style="font:bold 16px/25px Arial, Helvetica, sans-serif; color:#888; padding:0 0 23px;">
		Thanks for Subscribing to Theengirls.com We really appreciate it. We'll notify you of new content that comes out, and any news along the way.
	</td>
</tr>

{% endblock %}