blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
	 path('', views.view_posts, name = 'view_posts')
    ,path('post/<int:post_pk>/', views.view_post, name = 'view_post')
    # ,path('comments/<int:post_pk>/<int:page>/',views.view_comments, name = 'view_comments') --> Deprecated
]

comments/urls.py
from django.urls import path
from . import views

app_name = "comments"
urlpatterns = [
    path('comics/<int:comic_pk>/<int:page>/', views.view_comic_comments, name = 'view_comic_comments')
   ,path('post/<int:post_pk>/<int:page>/', views.view_post_comments, name = 'view_post_comments')
   ,path('view_conversations/<int:comment_pk>/<int:cur_set>/', views.view_conversations, name = 'view_conversations')
   ,path('view_conversations/<int:comment_pk>/', views.view_conversations, name = 'view_conversations')
   ,path('delete_comment/<int:comment_pk>/',views.delete_comment, name = 'delete_comment')
   ,path('like_comment/<int:comment_pk>/',views.like_comment, name = 'like_comment')
   ,path('num_likes/<int:comment_pk>/',views.num_likes, name = 'num_likes')

]

theengirls/urls.py
"""theengirls URL Configuration

"""
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views
from content import views as content_views, one_time_load

one_time_load.load_default_content()

urlpatterns = [
	path('', content_views.landing_page, name = "landing_page") # Home URL
	,path('comics/', include('comics.urls')) # comic app URLS
	,path('blog/',include('blog.urls')) # blog URLS
    ,path('comments/', include('comments.urls')) # comment URLS
    ,path('content/',include('content.urls')) # content URLS
    ,path('subscriptions/', include('subscriptions.urls')) # subscription URLS
	,path('admin/', admin.site.urls) # Django Admin URLS
    ,path('accounts/', include('django.contrib.auth.urls')) # Django User Auth URLS
    ,path('oauth/', include('social_django.urls', namespace='social'))  # Social App URLS 
    ,path('ckeditor/', include('ckeditor_uploader.urls')) # CK Editor
    ,path('privacy_policy/', views.privacy_policy, name = "privacy_policy")
    ,path('privacy_policy_source/', views.privacy_policy_source, name = "privacy_policy_source")
    ,path('logout/', views.logout_page, name="custom_logout")
    #,path('about/', about_page, name= "about")
    #,path('about_source/', about_source, name= "about_source")
    #,path('meet_the_engirls/', meet_the_engirls, name = "meet_the_engirls")
    #,path('meet_the_engirls_source/', meet_the_engirls_source, name = "meet_the_engirls_source")


]  
#if settings.DEBUG:
#    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # Media Files
#urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

#handler404 = error_404

blog/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils import timezone
from subscriptions.utils import send_new_post_email
import _thread as thread

"""
	Post model
"""
class Post(models.Model):
	
	# The title of the blog
	title = models.CharField(max_length=144, blank=False, null=False)
	
	# The text of the blog, as a rich editor
	body = RichTextUploadingField()
	
	# Created on Date
	created_on = models.DateField(default=timezone.now)
	
	# What category is the blog in?
	category = models.CharField(max_length=144, blank=True, null=True)

	# Send emails? 
	send_emails = models.BooleanField(default= True)

	class Meta:
		ordering = ('-created_on',)

	def __str__(self):
		return self.title

	"""
		Save 
			send emails
	"""
	def save(self):
		if self.send_emails:
			try:
				thread.start_new_thread( send_new_post_email,  (self.title, ) )
			except Exception as e:
				print("Unable to start new thread-{}\n Unable to send emails".format(str(e)))

		super(Post, self).save()	

comments/models.py
from django.db import models
from django.utils import timezone
from comics import models as comics_models
from blog import models as blog_models
from django.conf import settings
from django.core.exceptions import ValidationError

# Create your models here.
class Comment(models.Model):
    ComicPanel = models.ForeignKey(comics_models.ComicPanel ,on_delete=models.CASCADE, related_name='comic_panel_comments', blank = True, null = True)
    Post = models.ForeignKey(blog_models.Post, on_delete=models.CASCADE, related_name ='post_comments', blank = True, null = True)
    Comment = models.ForeignKey("self", on_delete=models.CASCADE, related_name = 'comment_comments', blank =True, null = True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE) 
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now = True, null = True)

    class Meta:
        ordering = ('-updated_on',)

    #Reference: https://stackoverflow.com/questions/53085645/django-one-of-2-fields-must-not-be-null
    #def clean(self):
    #	super().clean()
    #	if self.ComicPanel is None and self.Post is None and self.Comment is None:
    #		raise ValidationError('Comment must have reference to either a post, a comic, or another comment')


    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

class Comment_Like(models.Model):
	Comment = models.ForeignKey('Comment', on_delete = models.CASCADE, related_name = 'likes')
	count = models.IntegerField(blank = True, null = True)
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) 

comments/forms.py
from django import forms 

from .models import Comment
#from dal import autocomplete


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        widgets = {
          'body': forms.Textarea(attrs={'rows':2, 'cols':20}),
        }
    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['body'].label = "Say Something:" 


#Just use comment form for now
class ReplyForm(forms.ModelForm):
	body = forms.CharField(max_length = 3000, widget=forms.TextInput(attrs={'class':'reply_input_body'}))
	class Meta:
		model = Comment
		fields = ('body',)

	def __init__(self, *args, **kwargs):
		super(ReplyForm, self).__init__(*args, **kwargs)
		self.fields['body'].label = "" 

blog/views.py
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.exceptions import ObjectDoesNotExist
from comments.forms import CommentForm
from .models import Post #, Comment
from .filters import PostFilter
from django.http import HttpResponse, Http404
from django.conf import settings

###########################################################################
# Blog Views
###########################################################################


class Counter():
	_counter = 0
	def increment(self):
		_counter = _counter +1
	def decrement(self):
		_counter = _counter -1
	def count(self):
		return self._counter

# View post list
def view_posts(request):
	post_list = Post.objects.all()
	post_filter = PostFilter(request.GET, queryset=post_list)
	paginator = Paginator(post_filter.qs, settings.BLOG_POST_PAGINATION_COUNT )

	page = request.GET.get('page', 1)
	try:
		posts = paginator.page(page)
	except (PageNotAnInteger, TypeError):
		posts = paginator.page(1)
	except EmptyPage:
		posts = paginator.page(paginator.num_pages)

	return render(request, 'blog/view_posts.html', context = {'filter': post_filter, 'posts': posts, 'counter': Counter()})	

# View individual post
def view_post(request, post_pk =-1):
	p = None
	comment_form = None
	if request.method == 'GET':

		try:
			p = Post.objects.all().get(pk=post_pk)
		except ObjectDoesNotExist as e: 
			raise Http404

		comment_form = CommentForm()
	return render(request, "blog/view_post.html", context = {'post': p, 'comment_form':comment_form} )

comments/views.py
from django.shortcuts import render
from comics.models import ComicPanel
from blog.models import Post
from .models import Comment, Comment_Like
from .forms import CommentForm, ReplyForm
from django.http import HttpResponse, HttpResponseBadRequest, Http404, JsonResponse, HttpResponseForbidden
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import ensure_csrf_cookie


# Handles Posts to Blog comments and views
@ensure_csrf_cookie
def view_post_comments(request, post_pk=-1, page=1):
	comments_paginated = []
	reply_form = ReplyForm()
	max_comments = False

	try:
		p = Post.objects.all().get(pk=post_pk)
	except ObjectDoesNotExist as e:
		raise Http404

	if request.user.is_authenticated and Comment.objects.filter(user = request.user, Post = p).count() >= settings.MAX_COMMENTS_PER_USER_PER_PAGE:
		max_comments = True

	if request.method == 'POST' and request.user.is_authenticated:

		if max_comments:
			return HttpResponseForbidden("You've reached the maximum allotted comments for this item :/")	

		comment_form = CommentForm(request.POST)
		if comment_form.is_valid():
			# Create Comment object but don't save to database yet
			new_comment = comment_form.save(commit=False)
			# Assign the current post to the comment
			new_comment.Post = p
			# Save the comment to the database
			new_comment.user = request.user

			new_comment.save()

			return HttpResponse("Success")
		
		else:
			if settings.DEBUG:
				print("Comment form is not valid! HACKER!!! HACKKERRRR!")
			return HttpResponseBadRequest("bad request processing comment")
	
	elif request.method == 'POST' and not request.user.is_authenticated:
		return HttpResponseForbidden("Cannot post comment without login")
		
	comments = p.post_comments.all()

	# Show 5 per page
	paginator = Paginator(comments, settings.COMMENTS_PAGINATOR_COUNT)

	try:
		comments_paginated = paginator.page(page)
	except PageNotAnInteger:
		comments_paginated = paginator.page(1)
	except EmptyPage:
		comments_paginated = paginator.page(paginator.num_pages)
	except Exception as e:
		print(e)

	#template =  "comments/max_comments_posted.html" if max_comments else "comments/comment_comments.html"
	return render(request, "comments/comments.html", context = {
		'comments': comments_paginated, 
		'reply_form':reply_form, 
		'max_comments':max_comments } )	


"""
	retreive like count for a comment

	request must:
		1) Must have valid comment object pk -> return 404 otherwise
		2) Must be post request -> return 400 otherwise
		3) If GET request and valid comment -> return JSON output of count
"""
def num_likes(request, comment_pk=-1):
	try:
		comment = Comment.objects.all().get(pk=comment_pk)
	except ObjectDoesNotExist as e:
		if settings.DEBUG:
			print("Couldn't find comment")
		raise Http404

	if request.method == 'GET':
		like_count = Comment_Like.objects.filter(Comment = comment).count()
		return JsonResponse({'count':like_count})

	return HttpResponseBadRequest("Bad Request for this URL")


"""
	Like a Comment

	Return:  
"""
def like_comment(request,comment_pk=-1):
	try:
		comment = Comment.objects.all().get(pk=comment_pk)
	except ObjectDoesNotExist as e:
		if settings.DEBBUG:
			print("You fucked up with comment pk on like_comment")
		raise Http404

	if request.method == 'POST' and request.user.is_authenticated:
		comment_like = None
		# Does the like already exist? Remove it
		if Comment_Like.objects.filter(Comment = comment, user = request.user).exists():
			
			try:
				comment_like = Comment_Like.objects.all().get(Comment = comment, user = request.user)
			# There should only be one match... but just in case
			except MultipleObjectsReturned as e:
				return HttpResponseBadRequest("Server error processing likes")
			
			comment_like.delete()
		
		# This is a new like. Add it. Update the comment
		else:
			comment_like = Comment_Like.objects.create(Comment = comment, user = request.user)
			comment.updated_on = timezone.now()
			comment.save()

	elif request.method == 'POST' and not request.user.is_authenticated:
		return HttpResponseForbidden("Unauthenticated user")

	elif request.method != 'POST':
		return HttpResponseBadRequest("What the fuck are you trying to do?")

	return HttpResponse("")



"""
	Delete a comment

	request must:
		1) Must have valid comment object pk
		2) Must be post request
		3) Must have an authenticated user
		4) Must have an authenticated user that matches the comment's user
"""
def delete_comment(request, comment_pk =-1):
	try: 
		comment = Comment.objects.all().get(pk=comment_pk)
	except ObjectDoesNotExist as e:
		if settings.DEBUG:
			print("You fucked up with the comment pk")
		raise Http404

	if request.method == 'POST' and request.user.is_authenticated:
		if comment.user != request.user:
			return HttpResponseForbidden("Authenticated user does not match object user")
		
		comment.delete()

		return HttpResponse("Successfully deleted comment")

	elif request.method == 'POST' and not request.user.is_authenticated:
		return HttpResponseForbidden("User is not authenticated")

	elif request.method is not 'POST':
		return HttpResponseBadRequest("Bad request")



# View the replies in a comment, Post a comment
@ensure_csrf_cookie
def view_conversations(request, comment_pk=-1, cur_set = 1 ):
	reply_form = None 
	replies = []
	retreived_all = True
	max_comments = False

	try:
		comment = Comment.objects.all().get(pk=comment_pk)
	except ObjectDoesNotExist as e:
		raise Http404

	# Check to see if user has exceeded maximum number of comments
	if request.user.is_authenticated and Comment.objects.filter(user = request.user, Comment = comment).count() >= settings.MAX_COMMENTS_PER_USER_PER_PAGE:
		max_comments = True

	if request.method == 'GET':
		num_to_retreive = cur_set * 3
		total_replies = comment.comment_comments.all().count()
		
		if num_to_retreive >= total_replies:
			num_to_retreive = total_replies
			retreived_all = True
		else:
			retreived_all = False

		replies = comment.comment_comments.all()[:num_to_retreive]
		
		return render(request, "comments/replies.html", context = {
			'replies':replies, 
			'comment_pk': comment_pk, 
			'cur_set': cur_set, 
			'retreived_all' : retreived_all ,
			'max_comments':max_comments
			})


	if request.method == 'POST' and request.user.is_authenticated:

		#if settings.DEBUG:
		#	print("I made it to the post") 

		if max_comments:
			return HttpResponse("Reached maximum number of comments alloted for this item")			

		reply_form = ReplyForm(request.POST)
		if reply_form.is_valid():
			new_reply = reply_form.save(commit=False)
			new_reply.Comment = comment 
			new_reply.user = request.user 
			new_reply.save()

			# Updated comment
			comment.updated_on = timezone.now()
			comment.save()

			# On success 
			return HttpResponse("Successfully created a new reply!") 

		# If form is not valid
		else:
			return HttpResponseBadRequest("Issue processing reply")

	# If user is not authenticated
	if request.method == 'POST' and not request.user.is_authenticated:
		return HttpResponseForbidden("Cannot post comment without login")



# Handles comic panel comment view and posts to comments
def view_comic_comments(request, comic_pk =-1, page=1):
	comments_paginated = []
	reply_form = ReplyForm()
	max_comments = False

	try:
		cp = ComicPanel.objects.all().get(pk=comic_pk)
	except ObjectDoesNotExist as e: 
		raise Http404

	# Check if user has exceeded max comments for this post
	if request.user.is_authenticated and Comment.objects.filter(user = request.user, ComicPanel = cp).count() >= settings.MAX_COMMENTS_PER_USER_PER_PAGE:
		max_comments = True

	if request.method == 'POST' and request.user.is_authenticated:
		
		if max_comments:
			return HttpResponse("Maximum number of comments reached for item")

		comment_form = CommentForm(request.POST)
		if settings.DEBUG:
			print("Comment Form Errors: " + str(comment_form.errors))

		if comment_form.is_valid():

			# Create Comment object but don't save to database yet
			new_comment = comment_form.save(commit=False)
			# Assign the current post to the comment
			new_comment.ComicPanel = cp
			# Save the comment to the database
			new_comment.user = request.user

			new_comment.save()

			return HttpResponse("Success!")

		else:
			if settings.DEBUG:
				print("Comment form is not valid! HACKER!!! HACKKERRRR!")

			return HttpResponseBadRequest("bad request processing comment")

	elif request.method == 'POST' and not request.user.is_authenticated:
		return HttpResponseForbidden("Cannot post comment without login")

	comments = cp.comic_panel_comments.all()
	paginator = Paginator(comments, settings.COMMENTS_PAGINATOR_COUNT)

	try:
		comments_paginated = paginator.page(page)
	except PageNotAnInteger:
		comments_paginated = paginator.page(1)
	except EmptyPage:
		comments_paginated = paginator.page(paginator.num_pages)
	except Exception as e:
		print(e)

	return render(request, "comments/comments.html", context = {
		'comments': comments_paginated ,
		'reply_form':reply_form, 
		'max_comments':max_comments} );

blog/templates/blog/comments.html
  
<!DOCTYPE html>
<!-- Comment body based off bootstrap snippet: 
https://bootsnipp.com/snippets/g68X5
-->
<HTML lang="en">		 

<body>
<div class= container>
	<div class = "row">
		<div class="col-sm">
			<h1><small>{{ comments.paginator.count }} Comments </h1></small>
			<div class="comments-list">
				{% if comments %}
					{% for comment in comments %}
						<div class="media engirls_font_small">
							<small>Posted on: {{ comment.created_on|date:"d-m-Y" }} <br> by: {{ comment.name }}</small>
			                <div class="media-comment engirls_font_norm">
			                	<br>{{ comment.body }}
			                </div>

						</div>
						<hr>
					 {% endfor %}
				{% else %}
			    <div class = "media engirls_font_norm">
			    	 Start a conversation?
			    	 <hr>
			  	</div>
				{% endif %}
			<!-- end comment list -->
			</div>
		<!-- end col -->	
		</div>
	<!-- end row -->
	</div>

	<div class = row>
		<div class= "col-sm-3">
			<ul class="pagination">
				{% if comments.paginator.num_pages > 1 %}
					<div class = "col-xs-1 col-md-2 col-lg-3 engirls_font_norm">
						#
					</div>
					{% for num in comments.paginator.page_range %}
						<div class = "col-xs-1 col-md-2 col-lg-3 engirls_font_norm">
						{% if comments.number == num %}
							<!-- <button class="button-submit pagination_submit btn-outline-light btn-sm"> {{ num }}</button> -->
							 <a class="text-primary my_pagination_submit" href="#" > {{ num }} </a> 
						{% else %}
							<!-- <button class="button-submit pagination_submit btn-outline-dark btn-sm"> {{ num }}</button> -->
							<a class="text-secondary my_pagination_submit"  href = "#">{{ num }}</a> 
						{% endif %}
						</div>
					{% endfor %}
				{% endif %}
			</ul>
		</div>
	</div>	

<!-- end container -->
</div>



	

</body>

<script type="text/javascript">
$(".my_pagination_submit").on('click', function(e) {
    e.preventDefault();
    page_num = $.trim($(this).text());
    render_comment_list(page_num);

      return false;
  });
</script>

blog/templates/blog/view_post.html
{% extends "base.html" %}
{% block main_content %}

  <!-- Page Content -->
  <div class="container">

    {% if post %}

      <!-- Row for the header and subscribe -->
      <div class="row" style="overflow:hidden;">
        <div class="col">        
          <!-- Title -->
          <div class="mt-4 engirls_font_large">
            <h1 class = "float-left"><b>{{ post.title }}</b></h1> <br><small><p>{{ post.created_on }}</p>
               <p> Category: {{ post.category }}</p></small>
          </div>
          
        </div>

        <!-- Subscription -->
        <div class = "col-sm-5">
          <div class = "engirls_font_norm" id = "id_subscribe_wrapper" style= "width: 100% !important;"> </div>
        </div>

      </div>

      <!-- Row for the <hr> -->
      <div class = "row">
        <div class = "col">
          <hr>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-12">
          
          <div class = "shadow rounded px-4 py-4" style= "background-color: #FAFAFA; display:inline-block; width:100%">
           <!-- <div class="card-body"> -->
                <div class="">
                  {{ post.body | safe }} 
                </div>
            <!-- </div> -->
          </div>
        </div> 

         <!-- 3rd column - Comments -->
        <div class = "col-sm py-2">
          {% if user.is_authenticated %}
            <div class = "comment_form ml-2">
              <p>
                Logged as {{ user.username }}
                  
                <a href="/logout/?next={{request.path}}"><small>Logout</small></a>
              </p>
              <br>              
              <form action = "" method="POST"> 
                  {% csrf_token %}
                  {% for field in comment_form %}
                    <div class = "row engirls_font_small">
                      {{ field.label }}
                    </div>
                    <div class = "row">
                      {{ field }}
                  {% endfor %}  
                  <button id="post_comment" type="submit" class="button-submit btn-outline-dark btn-sm">post</button>
                    </div>
              </form>
            </div>
            <!-- if user is not authenticated -->
            {% else %}
              <div class="engirls_font_small">
                <div class = "container" id = "social_login_container">
                  Please Login to Comment:
                  <div class = "row">
                    <div class = "col-sm">
                      <a href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}"><img src="https://img.icons8.com/plasticine/48/000000/google-logo.png"></a>
                      <a href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}"><img src="https://img.icons8.com/doodle/48/000000/facebook-new.png"></a>
                    </div>                    
                  </div>
                </div> 
              </div>
            {% endif %}
            <div id = "comment_list"></div>
            <a name="comment_start"></a>
        </div>
                
       
    <!-- If no comic Pk -->
    {% else %}

      <div class = "col-sm-3"></div>
      <div class = "col-sm text-center">
        <div class = "engirls_font_large"> Looks like there is no Post here :( </div>
      </div>
      <div class = "col-sm-3"></div>

    {% endif %}

  </div>
  <!-- /.row -->
   
</div>
<!-- /.container -->

<script>


// Render the list of comments via ajax
function render_comment_list(page_num=1){
    $("#comment_list").load('/comments/post/{{ post.pk }}/' + page_num + '/');
  
}

// Post and render the comment list upon clickin the post comment button
$("#post_comment").on('click', function(e) {
    e.preventDefault();
    var form = $(this).closest("form");
     $.ajax({
            url: '/comments/post/{{ post.pk }}/1/',
            type: 'POST',
            data: form.serialize()
        }).done(function(data) {
          $('#id_body').val('');
          render_comment_list();
        });
      return false;
  });


$(document).ready(function(){
  // Make sure images aren't oversized
  $("img").addClass("img-fluid");
  render_comment_list();
  $("#id_subscribe_wrapper").load("/subscriptions/subscribe/");
});


 
</script>

{% endblock %}
{% block footer %}
    {% include "footer.html" %}
{% endblock %}

blog/templates/blog/view_posts.html
{% extends "base.html" %}
{% block main_content %}

{% if posts %}
<div class = "container-fluid">
<div class = "page-header text-center engirls_font_large pb-2 title_animation"> Engirls Blog</div> 

<div class = "row flex-xl-nowrap">
  <div id = "" class="pl-2 pb-4 slide_left" style = "">
    <p><b>Filter Posts</b></p>
    <div class = "">
      <div class = "engirls_font_norm">
          Category:
          <form class="form" method="GET">
            {% csrf_token %}
            {% for field in filter.form %}
              {{ field }}
              <button type="submit" id="id_submit_category" class="" style ="display:None;" >Filter</button>
            {% endfor %}       
          </form>      
      </div>
    </div>
  </div>
  <!-- Content section -->
  <div class = "col-lg-10 col-sm-12 col-md-12">
    {% for post in posts %}

           <a href = "{% url 'blog:view_post' post_pk=post.pk %}" style = "color:inherit;">
            <div class="jumbotron jumbotron-fluid shadow rounded" style = "background-color: #F7F6F6;" >
              <div class = "pl-3"><span class="badge badge-primary"> Category: {{ post.category }}</span> </div>    
              <br>
              <div class = "text-center">
               
                  <h1 class = "engirls_font_large"><p>{{ post.title }}</p></h1>
                  <div class = "engirls_font_small"> Created on: {{ post.created_on }} </div>   
                  <div class = "engirls_font_small mx-2">
                    {{ post.body|striptags|truncatewords:50 }}
                  </div> 
              </div>                
                                          
              </div>
          </a>
    {% endfor %}  
  </div>

<!-- end first row -->
</div>

  <div class = "row py-3 ml-2">
    <div class="pagination">
      {% if posts.paginator.num_pages > 1 %}
        <div class = "col-xs-1 col-md-2 col-lg-3 engirls_font_norm">
            #
        </div>
        {% for num in posts.paginator.page_range %}
          <div class = "col-xs-1 col-md-2 col-lg-3 engirls_font_norm">
            <!-- Current page number -->
            {% if posts.number == num %}
              <!-- If there is existing query parameters -->
              {% if 'category' in request.get_full_path %}
                <h5><a class="text-primary" href="{{ request.get_full_path }}&page={{ num }}" >{{ num }}</a></h5>
              {% else %}
                <h5><a class="text-primary" href="{% url 'blog:view_posts' %}?page={{ num }}" >{{ num }}</a></h5>
              {% endif %}

             <!-- Other page numbers -->
            {% else %}
              {% if 'category' in request.get_full_path %}
                <h5><a class="text-secondary" href="{{ request.get_full_path }}&page={{ num }}">{{ num }}</a></h5>
              {%  else %}
                <h5><a class="text-secondary" href="{% url 'blog:view_posts' %}?page={{ num }}" >{{ num }}</a></h5>
              {% endif %}

           {% endif %}
          </div>
       {% endfor %}
      {% endif %}
    <!-- pagination -->
    </div>
  <!-- row -->
  </div>

<!-- container -->
</div>

{% else %}
<div class = "container">
  <div class = "row">
    <div class = "col-sm-3"></div>
    <div class = "col-sm engirls_font_large">
      Looks like there are no blogs :(
    </div>
    <div class = "col-sm-3"></div>
  </div>
</div>
{% endif %}


<script>
  $("#id_category" ).change(function() {
    $("#id_submit_category").click();
  });
</script>
{% endblock %}

{% block footer %}
    {% include "footer.html" %}
{% endblock %}