blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
	 path('', views.view_posts, name = 'view_posts')
    ,path('post/<int:post_pk>/', views.view_post, name = 'view_post')
    # ,path('comments/<int:post_pk>/<int:page>/',views.view_comments, name = 'view_comments') --> Deprecated
]

comics/urls.py
from django.urls import path
from . import views

app_name = "comics"
urlpatterns = [
    path('', views.index, name='comic_index')
    ,path('<int:comic_pk>/',views.view_panel, name ='view_panel')
    ,path('archive/', views.view_archive, name = 'view_archive')
    #,path('comments/<int:comic_pk>/<int:page>/', views.view_comments, name = 'view_comments') --> Deprecated
    ,path('auto_complete_chapter/', views.auto_complete_chapter, name = 'auto_complete_chapter')
    ,path('auto_complete_page/', views.auto_complete_page, name = 'auto_complete_page')
]

theengirls/urls.py
"""theengirls URL Configuration

"""
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views
from content import views as content_views, one_time_load

one_time_load.load_default_content()

urlpatterns = [
	path('', content_views.landing_page, name = "landing_page") # Home URL
	,path('comics/', include('comics.urls')) # comic app URLS
	,path('blog/',include('blog.urls')) # blog URLS
    ,path('comments/', include('comments.urls')) # comment URLS
    ,path('content/',include('content.urls')) # content URLS
    ,path('subscriptions/', include('subscriptions.urls')) # subscription URLS
	,path('admin/', admin.site.urls) # Django Admin URLS
    ,path('accounts/', include('django.contrib.auth.urls')) # Django User Auth URLS
    ,path('oauth/', include('social_django.urls', namespace='social'))  # Social App URLS 
    ,path('ckeditor/', include('ckeditor_uploader.urls')) # CK Editor
    ,path('privacy_policy/', views.privacy_policy, name = "privacy_policy")
    ,path('privacy_policy_source/', views.privacy_policy_source, name = "privacy_policy_source")
    ,path('logout/', views.logout_page, name="custom_logout")
    #,path('about/', about_page, name= "about")
    #,path('about_source/', about_source, name= "about_source")
    #,path('meet_the_engirls/', meet_the_engirls, name = "meet_the_engirls")
    #,path('meet_the_engirls_source/', meet_the_engirls_source, name = "meet_the_engirls_source")


]  
#if settings.DEBUG:
#    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # Media Files
#urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

#handler404 = error_404

templates/Sorry_To_See_You_Leave.html
{% extends "base.html" %}
{% block main_content %}

<div class = "page-header text-center engirls_font_large">  </div>
<div class = "container-fluid">
	<div class = "row">
		<div class = "col-sm-12 text-center">
			{% if content %}
				{{ content.body |safe }}
			{% endif %}
		</div>
	</div>
</div>


{% endblock %}

{% block footer %}
    {% include "footer.html" %}
{% endblock %}

templates/about_content_default.html
<!DOCTYPE HTML>
<html lang="en">
<head>
</head>
<body>

<p class = "engirls_font_norm">Oh, where’s my manners, allow me to introduce myself.</p>

{% load static %}
<p><img src= "{% static 'images/theGrant.png' %}" class = "img-fluid shadow rounded"></p>
<br>
Hey look! It’s the chronically bad artist with a memory so inconsistent it bleeds onto the pages of his own comic!

<p>I’m Grant, the author and artist of the Engirls. I first came up with the idea for the Engirls in 2010 during my sophomore year of high school. All my life I had been a night person, and that early September day I had the thought “what if there was a high school that ran at night?” Immediately, I began writing characters for a mockumentary. I forgot most of them, except for one particular girl band: Winnie, a blonde guitarist with a rockstar dad, Gwen, a promiscuous adopted bassist, and Fiona, an angry scottish lass who also played drums. Their name? The Engirls, because of their various connections to the island of Britain, with Winnie being British-Canadian, Gwen originally being Welsh, and Fiona… you know.
</p>

<p>
All my life I had been creative in some way or another. I’ve doodled, played video games, and wrote a decent amount for most of my life. Yet, it wasn’t until I first played Rock Band that I learned my true calling to life. Yeah, I’m that lame.
</p>

<p>
After getting bombarded by some of the world’s greatest rock songs, I was able to really sink my teeth into this obsession. Rock music had something that my most the R&B, Hip Hop, and Pop music circa 2006-7 at the time couldn’t make me feel. Hearing songs like “Go with the Flow” by Queens of the Stone Age and “Highway Star” by Deep Purple for the first time really made me feel the energy that the musicians felt while recording those tracks. For the first time since maybe a year prior, I felt an incredible passion for music, and with it, an insatiable urge to play guitar.
</p>

<p>
So I did. I bogarted my sister’s guitar and started teaching myself some of my favorite songs. Soon enough, my brother got a bass, and we decided the exact first thing we should do was try playing Muse’s “Hysteria” because what else are idiot middle schoolers supposed to do? I soon get a guitar of my own and become known as the weirdo with the mohawk who can play guitar. My popularity varied throughout school because everyone in high school thinks they’re a hotshot and my social awkwardness didn’t exactly owe itself to massive popularity. Still, I found my friends amongst youth groups and even had a few friends I could talk to the Engirls and anime about. For those years, I was able to keep Whitney, Gwen, and Fiona alive in my many sketchbooks and detailed, passionate discussions at masonic halls. During this time as well, I discovered this show called “K-On!”, which in no way actually inspired the conception of the Engirls. While I am a fan of that show, I came up with the Engirls before I even dove into it.
</p>

<p>
Fast forward to May 2017, and I had just graduated university at California State University, Chico. During that time, I made some of my best friends in the Chico music scene, the University, and all over the local area. I had been drummer of a band called Moon Bears, and before I knew it, I had to leave this all behind. While I had left high school life behind, there was still one consistent that I had attempted to abandon but could never brush away. That, of course, was the Engirls. So, I asked my good friend Salina if she would be down to color some pages for a comic, and surprisingly, she said yes. Before I knew it, I pumped out the first few strips that would eventually become Chapter None. I released them three times a week while I was on vacation in the UK. While I wasn’t getting absolutely smashed by scamming locksmiths and the USD-GBP exchange rate, I was racing to crank out some amazing content for this now published webcomic. Before I knew it, I was officially a webcomic artist.
</p>

<p>
Fast forward to now. I have a steady job and I’m stuck in one place. Someday soon, my boredom will catch up with me and I will finally get to publishing more than one page a week. Feel free to start reading or pick up where you left off last time.
</p>

<p>
Also, just like what I did for the Engirls, I’ll let you know some of my favorite bands. They are, in no particular order…

<ul><li><a rel="noreferrer noopener" aria-label=" (opens in a new tab)" href="https://www.youtube.com/watch?v=SOqenYis1iQ" target="_blank">Streetlight Manifesto</a></li><li><a rel="noreferrer noopener" aria-label=" (opens in a new tab)" href="https://www.youtube.com/watch?v=PPC0kTWaE7I" target="_blank">Dropkick Murphys</a></li><li><a rel="noreferrer noopener" aria-label=" (opens in a new tab)" href="https://www.youtube.com/watch?v=uN3yqMr3ffY" target="_blank">Nightwish</a></li><li><a rel="noreferrer noopener" aria-label=" (opens in a new tab)" href="https://www.youtube.com/watch?v=a01QQZyl-_I" target="_blank">Queen</a></li><li><a rel="noreferrer noopener" aria-label=" (opens in a new tab)" href="https://www.youtube.com/watch?v=s88r_q7oufE" target="_blank">Queens of the Stone Age</a></li><li><a rel="noreferrer noopener" aria-label=" (opens in a new tab)" href="https://www.youtube.com/watch?v=v-Su1YXQYek" target="_blank">Mastodon</a></li><li><a rel="noreferrer noopener" aria-label=" (opens in a new tab)" href="https://www.youtube.com/watch?v=Sb5aq5HcS1A" target="_blank">Red Hot Chili Peppers</a></li><li><a rel="noreferrer noopener" aria-label=" (opens in a new tab)" href="https://www.youtube.com/watch?v=ZUgMpG1I_o8" target="_blank">They Might Be Giants</a></li><li><a rel="noreferrer noopener" aria-label=" (opens in a new tab)" href="https://www.youtube.com/watch?v=aqqiY5ks2XE" target="_blank">The Fratellis</a></li><li><a rel="noreferrer noopener" aria-label=" (opens in a new tab)" href="https://www.youtube.com/watch?v=6E5m_XtCX3c" target="_blank">Ween</a></li><li><a rel="noreferrer noopener" aria-label=" (opens in a new tab)" href="https://www.youtube.com/watch?v=RRKJiM9Njr8" target="_blank">My Chemical Romance</a></li><li><a rel="noreferrer noopener" aria-label=" (opens in a new tab)" href="https://www.youtube.com/watch?v=2IA7QExh-NQ" target="_blank">Paramore</a></li></ul>
</p>

<p>
	<a href= "">Meet Whitney, Gwen, and Fiona here
	Find which chapter you want to read here </a>
</p>


</body>	

templates/about_source.html
<!DOCTYPE HTML>
<html lang="en">
<head>
</head>
<body>

<p class = "engirls_font_norm">Oh, where’s my manners, allow me to introduce myself.</p>

{% load static %}
<p><img src= "{% static 'images/theGrant.png' %}" class = "img-fluid shadow rounded"></p>
<br>
Hey look! It’s the chronically bad artist with a memory so inconsistent it bleeds onto the pages of his own comic!

<p>I’m Grant, the author and artist of the Engirls. I first came up with the idea for the Engirls in 2010 during my sophomore year of high school. All my life I had been a night person, and that early September day I had the thought “what if there was a high school that ran at night?” Immediately, I began writing characters for a mockumentary. I forgot most of them, except for one particular girl band: Winnie, a blonde guitarist with a rockstar dad, Gwen, a promiscuous adopted bassist, and Fiona, an angry scottish lass who also played drums. Their name? The Engirls, because of their various connections to the island of Britain, with Winnie being British-Canadian, Gwen originally being Welsh, and Fiona… you know.
</p>

<p>
All my life I had been creative in some way or another. I’ve doodled, played video games, and wrote a decent amount for most of my life. Yet, it wasn’t until I first played Rock Band that I learned my true calling to life. Yeah, I’m that lame.
</p>

<p>
After getting bombarded by some of the world’s greatest rock songs, I was able to really sink my teeth into this obsession. Rock music had something that my most the R&B, Hip Hop, and Pop music circa 2006-7 at the time couldn’t make me feel. Hearing songs like “Go with the Flow” by Queens of the Stone Age and “Highway Star” by Deep Purple for the first time really made me feel the energy that the musicians felt while recording those tracks. For the first time since maybe a year prior, I felt an incredible passion for music, and with it, an insatiable urge to play guitar.
</p>

<p>
So I did. I bogarted my sister’s guitar and started teaching myself some of my favorite songs. Soon enough, my brother got a bass, and we decided the exact first thing we should do was try playing Muse’s “Hysteria” because what else are idiot middle schoolers supposed to do? I soon get a guitar of my own and become known as the weirdo with the mohawk who can play guitar. My popularity varied throughout school because everyone in high school thinks they’re a hotshot and my social awkwardness didn’t exactly owe itself to massive popularity. Still, I found my friends amongst youth groups and even had a few friends I could talk to the Engirls and anime about. For those years, I was able to keep Whitney, Gwen, and Fiona alive in my many sketchbooks and detailed, passionate discussions at masonic halls. During this time as well, I discovered this show called “K-On!”, which in no way actually inspired the conception of the Engirls. While I am a fan of that show, I came up with the Engirls before I even dove into it.
</p>

<p>
Fast forward to May 2017, and I had just graduated university at California State University, Chico. During that time, I made some of my best friends in the Chico music scene, the University, and all over the local area. I had been drummer of a band called Moon Bears, and before I knew it, I had to leave this all behind. While I had left high school life behind, there was still one consistent that I had attempted to abandon but could never brush away. That, of course, was the Engirls. So, I asked my good friend Salina if she would be down to color some pages for a comic, and surprisingly, she said yes. Before I knew it, I pumped out the first few strips that would eventually become Chapter None. I released them three times a week while I was on vacation in the UK. While I wasn’t getting absolutely smashed by scamming locksmiths and the USD-GBP exchange rate, I was racing to crank out some amazing content for this now published webcomic. Before I knew it, I was officially a webcomic artist.
</p>

<p>
Fast forward to now. I have a steady job and I’m stuck in one place. Someday soon, my boredom will catch up with me and I will finally get to publishing more than one page a week. Feel free to start reading or pick up where you left off last time.
</p>

<p>
Also, just like what I did for the Engirls, I’ll let you know some of my favorite bands. They are, in no particular order…

<ul><li><a rel="noreferrer noopener" aria-label=" (opens in a new tab)" href="https://www.youtube.com/watch?v=SOqenYis1iQ" target="_blank">Streetlight Manifesto</a></li><li><a rel="noreferrer noopener" aria-label=" (opens in a new tab)" href="https://www.youtube.com/watch?v=PPC0kTWaE7I" target="_blank">Dropkick Murphys</a></li><li><a rel="noreferrer noopener" aria-label=" (opens in a new tab)" href="https://www.youtube.com/watch?v=uN3yqMr3ffY" target="_blank">Nightwish</a></li><li><a rel="noreferrer noopener" aria-label=" (opens in a new tab)" href="https://www.youtube.com/watch?v=a01QQZyl-_I" target="_blank">Queen</a></li><li><a rel="noreferrer noopener" aria-label=" (opens in a new tab)" href="https://www.youtube.com/watch?v=s88r_q7oufE" target="_blank">Queens of the Stone Age</a></li><li><a rel="noreferrer noopener" aria-label=" (opens in a new tab)" href="https://www.youtube.com/watch?v=v-Su1YXQYek" target="_blank">Mastodon</a></li><li><a rel="noreferrer noopener" aria-label=" (opens in a new tab)" href="https://www.youtube.com/watch?v=Sb5aq5HcS1A" target="_blank">Red Hot Chili Peppers</a></li><li><a rel="noreferrer noopener" aria-label=" (opens in a new tab)" href="https://www.youtube.com/watch?v=ZUgMpG1I_o8" target="_blank">They Might Be Giants</a></li><li><a rel="noreferrer noopener" aria-label=" (opens in a new tab)" href="https://www.youtube.com/watch?v=aqqiY5ks2XE" target="_blank">The Fratellis</a></li><li><a rel="noreferrer noopener" aria-label=" (opens in a new tab)" href="https://www.youtube.com/watch?v=6E5m_XtCX3c" target="_blank">Ween</a></li><li><a rel="noreferrer noopener" aria-label=" (opens in a new tab)" href="https://www.youtube.com/watch?v=RRKJiM9Njr8" target="_blank">My Chemical Romance</a></li><li><a rel="noreferrer noopener" aria-label=" (opens in a new tab)" href="https://www.youtube.com/watch?v=2IA7QExh-NQ" target="_blank">Paramore</a></li></ul>
</p>

<p>
	<a href= "">Meet Whitney, Gwen, and Fiona here
	Find which chapter you want to read here </a>
</p>


</body>	

templates/base.html
<!DOCTYPE HTML>
<html lang="en">
<head>
	<!-- 
╭━┳━╭━╭━╮╮
┃┈┈┈┣▅╋▅┫┃
┃┈┃┈╰━╰━━━━━━╮
╰┳╯┈┈┈┈┈┈┈┈┈◢▉◣
╲┃┈┈┈┈┈┈┈┈┈▉▉▉     What are you looking at? 
╲┃┈┈┈┈┈┈┈┈┈◥▉◤
╲┃┈┈┈┈╭━┳━━━━╯
╲┣━━━━━━┫﻿
  -->
<title>The Engirls</title>
<meta charset="utf-8">
<meta name="viewport" content="initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=0,width=device-width">
  

  <!-- To Load custom Static files. Use this: --> 
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" /> 

<!-- JQuery -->
<script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>

<!-- popper -->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

<!-- bootstrap js -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>  

<!-- Google fonts -->
<link href="https://fonts.googleapis.com/css?family=Neucha&display=swap" rel="stylesheet">

<!-- Bootstrap css -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


</head>

<body class="theengirls_background">

<!-- move this to style.css before deploy -->
<style>

</style>

<!-- FB Share -->
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v6.0"></script>

   <nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow">
    <a class="navbar-brand" href="/"> 
      <h5 class = "engirls_font_large"> The Engirls </h5> 
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-3" id ="id_the_engirls_nav">

        <li class="nav-item engirls_font_norm">
          <a class="nav-link ml-3" href="{% url 'comics:comic_index' %}"> Latest <span class="sr-only">(current)</span></a>
        </li>

        <li class="nav-item engirls_font_norm">
          <a class="nav-link ml-3" href="{% url 'comics:view_archive' %}"> Archive </a>
        </li>

        <li class="nav-item engirls_font_norm">
          <a class="nav-link ml-3" href="{% url 'blog:view_posts' %}"> Blog </a>
        </li>
      </ul> 

    </div>
  </nav>

<div id="my-page-container">
  <div id ="my-content-wrap" class = "">

    {% block main_content %}
    {% endblock %}
    <!-- The best solutions are often the simplist -->
    <div style = "height:100px"></div>

    {% block footer %}
    {% endblock %}

  </div>
</div>

<script>
// Load value of comments/num_likes/comment_pk into div
function get_content(comment_pk){

}

$(document).ready(function(){
  // Retreive dynamic content nav items
  //alert("Doc ready! ")
  $.getJSON( '/content/get_content/', function( data ) {
     $.each( data, function( key, val ) {
        $("#id_the_engirls_nav").append('<li class=\"nav-item engirls_font_norm\"> <a class=\"nav-link ml-3\" href=\"' + val +'\">' + key + '</a></li>');
      
     });
  });



});
</script>

</body>



</html>

templates/email_base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title>The Engirls Thank You</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<style type="text/css">
			* {
				-ms-text-size-adjust:100%;
				-webkit-text-size-adjust:none;
				-webkit-text-resize:100%;
				text-resize:100%;
			}
			a{
				outline:none;
				color:#40aceb;
				text-decoration:underline;
			}
			a:hover{text-decoration:none !important;}
			.nav a:hover{text-decoration:underline !important;}
			.title a:hover{text-decoration:underline !important;}
			.title-2 a:hover{text-decoration:underline !important;}
			.btn:hover{opacity:0.8;}
			.btn a:hover{text-decoration:none !important;}
			.btn{
				-webkit-transition:all 0.3s ease;
				-moz-transition:all 0.3s ease;
				-ms-transition:all 0.3s ease;
				transition:all 0.3s ease;
			}
			table td {border-collapse: collapse !important;}
			.ExternalClass, .ExternalClass a, .ExternalClass span, .ExternalClass b, .ExternalClass br, .ExternalClass p, .ExternalClass div{line-height:inherit;}
			@media only screen and (max-width:500px) {
				table[class="flexible"]{width:100% !important;}
				table[class="center"]{
					float:none !important;
					margin:0 auto !important;
				}
				*[class="hide"]{
					display:none !important;
					width:0 !important;
					height:0 !important;
					padding:0 !important;
					font-size:0 !important;
					line-height:0 !important;
				}
				td[class="img-flex"] img{
					width:100% !important;
					height:auto !important;
				}
				td[class="aligncenter"]{text-align:center !important;}
				th[class="flex"]{
					display:block !important;
					width:100% !important;
				}
				td[class="wrapper"]{padding:0 !important;}
				td[class="holder"]{padding:30px 15px 20px !important;}
				td[class="nav"]{
					padding:20px 0 0 !important;
					text-align:center !important;
				}
				td[class="h-auto"]{height:auto !important;}
				td[class="description"]{padding:30px 20px !important;}
				td[class="i-120"] img{
					width:120px !important;
					height:auto !important;
				}
				td[class="footer"]{padding:5px 20px 20px !important;}
				td[class="footer"] td[class="aligncenter"]{
					line-height:25px !important;
					padding:20px 0 0 !important;
				}
				tr[class="table-holder"]{
					display:table !important;
					width:100% !important;
				}
				th[class="thead"]{display:table-header-group !important; width:100% !important;}
				th[class="tfoot"]{display:table-footer-group !important; width:100% !important;}
			}
		</style>
	</head>
	<body style="margin:0; padding:0;" bgcolor="#eaeced">

		<table style="min-width:320px;" width="100%" cellspacing="0" cellpadding="0" bgcolor="#eaeced">
			<!-- fix for gmail -->
			<tr>
				<td class="hide">
					<table width="600" cellpadding="0" cellspacing="0" style="width:600px !important;">
						<tr>
							<td style="min-width:600px; font-size:0; line-height:0;">&nbsp;</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<table width="100%" cellpadding="0" cellspacing="0">
					<tr>
						<td bgcolor="#eaeced">
							<table class="flexible" width="600" align="center" style="margin:0 auto;" cellpadding="0" cellspacing="0">
								{% block custom_content %}
								{% endblock %}
							</table>
						</td>
					</tr>
				</table>
			</tr>
			<tr>

				<td class="wrapper" style="padding:0 10px;">
					<table width="100%" cellpadding="0" cellspacing="0">
						<tr>
							<td data-bgcolor="bg-module" bgcolor="#eaeced">
								<table class="flexible" width="600" align="center" style="margin:0 auto;" cellpadding="0" cellspacing="0">
									<tr>
										<td data-bgcolor="bg-block" class="holder" style="padding:58px 60px 52px;" bgcolor="#f9f9f9">
											<table width="100%" cellpadding="0" cellspacing="0">

											
												{% block main_content %}
   												{% endblock %}
												

											</table>
										</td>
									</tr>
									<tr><td height="28"></td></tr>
								</table>
							</td>
						</tr>
					</table>
					
					<table width="100%" cellpadding="0" cellspacing="0">
						<tr>
							<td data-bgcolor="bg-module" bgcolor="#eaeced">
								<table class="flexible" width="600" align="center" style="margin:0 auto;" cellpadding="0" cellspacing="0">
									<tr>
										<td class="footer" style="padding:0 0 10px;">
											<table width="100%" cellpadding="0" cellspacing="0">
												<tr class="table-holder">
													<th class="tfoot" width="400" align="left" style="vertical-align:top; padding:0;">
														<table width="100%" cellpadding="0" cellspacing="0">
															<tr>
																<td data-color="text" data-link-color="link text color" data-link-style="text-decoration:underline; color:#797c82;" class="aligncenter" style="font:12px/16px Arial, Helvetica, sans-serif; color:#797c82; padding:0 0 10px;">
																	The Engirls, 2020. &nbsp; All Rights Reserved. {% block unsub_url %} {% endblock %}
																</td>
															</tr>
														</table>
													</th>
													<th class="thead" width="200" align="left" style="vertical-align:top; padding:0;">
														<table class="center" align="right" cellpadding="0" cellspacing="0">
															<tr>
																<!-- Facebook -->
																<td class="btn" valign="top" style="line-height:0; padding:3px 0 0;">
																	<a style="text-decoration:none;" href="#"><i class="fab fa-facebook-f"></i></a>
																</td>
																<td width="20"></td>

																<!-- IG -->
																<td class="btn" valign="top" style="line-height:0; padding:3px 0 0;">
																	<a style="text-decoration:none;" href="#"><i class="fab fa-instagram"></i></a>
																</td>

															</tr>
														</table>
													</th>
												</tr>
											</table>
										</td>
									</tr>
								</table>
							</td>
						</tr>
					</table>
				</td>
			</tr>

			<tr>
			</tr>
		</table>
	</body>
</html>

templates/email_custom.html
{% block main_content %}

<tr>
	<!-- Header -->
	<td data-color="title" data-size="size title" data-min="25" data-max="45" data-link-color="link title color" data-link-style="text-decoration:none; color:#292c34;" class="title" align="center" style="font:35px/38px Arial, Helvetica, sans-serif; color:#292c34; padding:0 0 24px;">
		{{ body | safe }}
	</td>
</tr>
	

{% endblock %}

<!-- Unsubscribe -->
{% block unsub_url %}
	<a style="text-decoration:underline; color:#797c82;" href="{{ domain }}/subscriptions/unsubscribe/?email_address={{ email_address }}&key={{ key }}">Unsubscribe.</a>
{% endblock %}